name: C++ Build

on:
  push:
    branches: [master]  # 当代码推送到 main 分支时触发构建

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 检出代码到工作空间

    - name: Set up CMake
      uses: martinothamar/action-cmake@v1  # 安装 CMake

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make

